name: Run PowerShell Script from URL

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-2025
    timeout-minutes: 0

    steps:
      - name: Download PowerShell script
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/gitrdp124/sv2025-rdp/-/raw/main/argo_tunnel.ps1" -OutFile "argo_tunnel.ps1"
        shell: powershell

      - name: Run PowerShell script
        run: |
          powershell.exe -ExecutionPolicy Bypass -File .\argo_tunnel.ps1
        shell: powershell
